/** @file RRNAfold_opts.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef RRNAFOLD_OPTS_H
#define RRNAFOLD_OPTS_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef RRNAFOLD_PARSER_PACKAGE
/** @brief the program name */
#define RRNAFOLD_PARSER_PACKAGE "RRNAFold"
#endif

#ifndef RRNAFOLD_PARSER_VERSION
/** @brief the program version */
#define RRNAFOLD_PARSER_VERSION "0.1.0"
#endif

/** @brief Where the command line options are stored */
struct RRNAfold_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * input_file_arg;	/**< @brief Path to file containing the sequences to be folded\n (default='input.dat').  */
  char * input_file_orig;	/**< @brief Path to file containing the sequences to be folded\n original value given at command line.  */
  const char *input_file_help; /**< @brief Path to file containing the sequences to be folded\n help description.  */
  float temperature_arg;	/**< @brief Temperature passed to the viennaFold secondary structure algorithm\n (default='30.0').  */
  char * temperature_orig;	/**< @brief Temperature passed to the viennaFold secondary structure algorithm\n original value given at command line.  */
  const char *temperature_help; /**< @brief Temperature passed to the viennaFold secondary structure algorithm\n help description.  */
  int fold_type_arg;	/**< @brief Dictates the type of output returned (default='1').  */
  char * fold_type_orig;	/**< @brief Dictates the type of output returned original value given at command line.  */
  const char *fold_type_help; /**< @brief Dictates the type of output returned help description.  */
  char * output_file_arg;	/**< @brief Name of file where secondary structure coordinates are outputed\n (default='output.dat').  */
  char * output_file_orig;	/**< @brief Name of file where secondary structure coordinates are outputed\n original value given at command line.  */
  const char *output_file_help; /**< @brief Name of file where secondary structure coordinates are outputed\n help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int input_file_given ;	/**< @brief Whether input-file was given.  */
  unsigned int temperature_given ;	/**< @brief Whether temperature was given.  */
  unsigned int fold_type_given ;	/**< @brief Whether fold-type was given.  */
  unsigned int output_file_given ;	/**< @brief Whether output-file was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct RRNAfold_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure RRNAfold_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure RRNAfold_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *RRNAfold_args_info_purpose;
/** @brief the usage string of the program */
extern const char *RRNAfold_args_info_usage;
/** @brief all the lines making the help output */
extern const char *RRNAfold_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int RRNAfold_parser (int argc, char * const *argv,
  struct RRNAfold_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use RRNAfold_parser_ext() instead
 */
int RRNAfold_parser2 (int argc, char * const *argv,
  struct RRNAfold_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int RRNAfold_parser_ext (int argc, char * const *argv,
  struct RRNAfold_args_info *args_info,
  struct RRNAfold_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int RRNAfold_parser_dump(FILE *outfile,
  struct RRNAfold_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int RRNAfold_parser_file_save(const char *filename,
  struct RRNAfold_args_info *args_info);

/**
 * Print the help
 */
void RRNAfold_parser_print_help(void);
/**
 * Print the version
 */
void RRNAfold_parser_print_version(void);

/**
 * Initializes all the fields a RRNAfold_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void RRNAfold_parser_params_init(struct RRNAfold_parser_params *params);

/**
 * Allocates dynamically a RRNAfold_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized RRNAfold_parser_params structure
 */
struct RRNAfold_parser_params *RRNAfold_parser_params_create(void);

/**
 * Initializes the passed RRNAfold_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void RRNAfold_parser_init (struct RRNAfold_args_info *args_info);
/**
 * Deallocates the string fields of the RRNAfold_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void RRNAfold_parser_free (struct RRNAfold_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int RRNAfold_parser_required (struct RRNAfold_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* RRNAFOLD_OPTS_H */
